### ISSUE TITLE
Font size trick to make rem units = px

### ISSUE THREAD

**Issue by StefanPietzner** [nikita-kit/nikita-css#15]
If the font size of the :root is less than 9px, than the webkit browsers will set the font size! On this point we cant overwrite this font size rule. Chrome set the font size to 6px and safari to 9px. So all off our rem units become to multiplied with 6 or 9. That not really cool.

**Comment by axten** [comment]
agree, we have to find another solution...
@hermanndettmann @ceehaupt
what about setting html element font-size to 10px, then we have 10px = 1rem ?

**Comment by StefanPietzner** [comment]
In europapark project i set the font size of root to 62.5%. It's equal to 10px. So we can 
divide all rem's by 10. It's an easy way - in my opinion.

**Comment by axten** [comment]
we should go with 10px because  62.5% ist not working correctly in IE

**Comment by StefanPietzner** [comment]
Hm, i will check this

**Comment by hermanndettmann** [comment]
But regarding accessibility I think it's better to use a percentage based value so when the user increases the default font size of their browser everything follows. For IE we could use the following media query to set a pixel based value:

`@media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {
        font-size: 10px
 }`

And hopefully at some not so far point in the future we can remove that special condition when IE finally bites the dust.

**Comment by axten** [comment]
are you sure that this impacts browser accessibility features?

**Comment by axten** [comment]
ok, after testing this, final solution should be: 
```
html {
    font-size: 62.5%;
}

// fix IE
@media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) { 
    html {
        font-size: 10px;
    }    
}
```
