### ISSUE TITLE
c- prefix for components

### ISSUE THREAD

**Issue by hermanndettmann** [nikita-kit/nikita-css#8]
With the introduction of the components folder in the Nikita stack I think this should be reflected in the CSS class naming as well. I would suggest to distinguish between blocks and components by introducing a "c-" prefix for all styles that are related to a component. For example each stylesheet that lays next to a component in the components folder. That would make stylesheets easier to find when you only have the classname and you don't want to scroll through a big amount of block stylesheets.

What do you think?

**Comment by axten** [comment]
agree :)
cc @ceehaupt

**Comment by ceehaupt** [comment]
i would even say c-- to have a unique one.

**Comment by axten** [comment]
great, so all we need is a PR here ;)

**Comment by axten** [comment]
discussed this again with @hermanndettmann and we think we should stay with `b-` @ceehaupt
